### PR TITLE
Added support for delayed responses

### PR DESCRIPTION
**Pull request by faustomilletari**
Especially useful for slow services that are returning results after several seconds.

In this case the server sends out a DelayedResponse message that the client has to handle. This message contains a request ID. it's the task of the client to start pining the server at http(s)://hostname/responses with a POST request containing the request ID to see if the results are ready.

we want the Slicer UI not to hang while this is done. We have used a QTimer to launch said request once every 1000ms to ping the server and enquiry about the situation with the prediction. 

at this point either one of two things will happen:
1 - the response is not yet ready. server will send a new delayed response and trigger a new timer.
2 - there is a valid response. this is parsed as usual. 

Note that this should be used only for servers that are very slow because this sort of active polling of the resource may take more time than the actual processing time for the request.

### CODE REVIEW

**Comment by faustomilletari** [comment]
See this for server side: https://github.com/faustomilletari/TOMAAT/pull/21

**Comment by faustomilletari** [comment]
Tagging @j-frei on this PR

**Comment by j-frei** [comment]
Nice work!
But by using DelayedResponses and QTimer, does it becomes difficult for another Slicer plugin to use TOMAAT as part of a larger processing pipeline?
(because the whole send/receive process is not blocking the program flow anymore...)

**Comment by faustomilletari** [comment]
It might, but keep in mind that we want to have the Slicer extension separated from the "real" client. 

I was hoping to be able to deliver client functionality into TOMAAT package, meaning that even the 3d slicer version of it will need to use those functionalities eventually (and therefore import tomaat into the 3d-slicer extension code). I wanted also to ship a text-ui based client with tomaat package.

Hopefully this will allow people to build also their own clients.

What do you think?


Fausto

**Pull request merged**
