### PR TITLE
Switch from HTTP to HTTPS

### PR DESCRIPTION
**Pull request by j-frei**
Complementary update for Slicer

### CODE REVIEW

**Comment by j-frei** [comment]
Consider that this update is only compatible with the latest nightly builds of Slicer where Python 3 is in use.

**Comment by faustomilletari** [comment]
will this break retro compatibility with older versions of slicer?

**Comment by j-frei** [comment]
Unfortunately, yes.

- I couldn't get pyOpenSSL installed within old Slicer versions
- The nightly Slicer versions (4.11) expose an API for pip (slicer.util.pip_install("requests") ) which is not exposed by earlier versions. I edited the file "dependencies" to make use of the new function.

**Comment by j-frei** [comment]
I've added some updates for Python 2 compatibility. I've tested this with Slicer 4.9. Should be fine now...

**Pull request merged**
